color: null
description: null
fieldLayouts:
  08401f9f-0818-4686-90ad-0a17f17fc92a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-07T05:08:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 47874a18-9b2b-47c4-94dd-bb40a3ce1d5b # cert_title
            handle: cert_title
            includeInCards: false
            instructions: null
            label: 'Certificate title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2d13bbd-4148-4764-9e0d-f0f4339bfd2b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-07T05:08:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 781e8262-af2f-499d-a977-0f68a5aa927e # Certificate description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86c266a5-313e-469b-b3db-886803ea218f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-07T05:11:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 693a5968-6069-4323-9bae-d544221573df # Certificate image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66fd73d0-ab3d-4749-a7b4-c5f6c960e0f1
            userCondition: null
            warning: null
            width: 100
        name: Контент
        uid: 2cdadd87-73bd-40b8-b32c-088d8fd001ab
        userCondition: null
handle: certificates
hasTitleField: false
icon: award
name: Certificates
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{cert_title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
