color: null
description: null
fieldLayouts:
  6bb3e417-f0ea-4a20-afe8-8cfff833ff55:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-06T12:21:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4ced3b62-49ce-461b-8492-daac9dbfde92 # Service title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7b380aa-914a-40c4-b6b4-7c1cd315226f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-06T12:21:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 00a82a55-1957-4857-9134-774422d01896 # Card description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a04fe539-26d6-48c6-ab04-73292e032178
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-06T12:24:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a234ede-52ab-441a-a455-38321b501bea # ServiceImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d365d5f8-8dc4-473b-a09c-de104826acf2
            userCondition: null
            warning: null
            width: 100
        name: Контент
        uid: e81c0b17-82b5-4495-ad64-bfc1ab1bae5c
        userCondition: null
handle: services
hasTitleField: false
icon: null
name: Services
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{service_title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
