altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  95ae659c-c14b-42ea-b2bc-f74963a65258:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-07T05:08:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3d8452db-e906-4ed6-8f1b-aee24ca48c43
            userCondition: null
            warning: null
            width: 100
        name: Контент
        uid: 7277b0cc-5922-41a5-9c90-7f6645adcfb6
        userCondition: null
fs: certificates
handle: certificates
name: Certificates
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
