altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fbe73f69-5199-4e80-a03a-7946d940f165:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-07T05:12:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: db62eefe-3aa8-4905-a7a4-4c33a46be738
            userCondition: null
            warning: null
            width: 100
        name: Контент
        uid: fe3e8a87-9b52-4988-9202-eccf982371c1
        userCondition: null
fs: diplomas
handle: diplomas
name: Diplomas
sortOrder: 4
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
