altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  2b085a4d-7611-47b7-ab75-bf845593aac0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-06T10:39:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3861a72c-1eac-46b6-9ac9-f29bcb228a1a
            userCondition: null
            warning: null
            width: 100
        name: Контент
        uid: 3820b46f-d0d6-4a32-9c6f-e4d6e55d4189
        userCondition: null
fs: heroImages
handle: heroimages
name: HeroImages
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
