altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  0dadba89-07ac-44ab-8345-991f4de92371:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-06T12:22:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4eb8bc88-01ca-49d5-b2e9-518bae2e09c0
            userCondition: null
            warning: null
            width: 100
        name: Контент
        uid: 4c366a4e-7bd3-4510-9f68-f08c1e5e233e
        userCondition: null
fs: services
handle: services
name: Services
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
