altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  006fcabd-11a6-4501-baca-aa9bcdf10007:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-07T05:47:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5fd1211a-d191-4b80-8507-a067c78a070a
            userCondition: null
            warning: null
            width: 100
        name: Контент
        uid: b089c84b-1a94-4994-9cbc-c7702cb8dbf0
        userCondition: null
fs: siteinfo
handle: siteinfo
name: SiteInfo
sortOrder: 5
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
