columnSuffix: null
handle: aboutText
instructions: null
name: 'About text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
