columnSuffix: null
handle: seoDescription
instructions: null
name: 'Seo description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
