defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 81a7f22c-2259-4665-9baf-44d4dff99977 # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: true
    template: about/_entry.twig
    uriFormat: about
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: true
    template: about/_entry.twig
    uriFormat: about
type: single
