defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c4b7986f-30f9-4b90-b24d-5d559e1718b8 # Courses
handle: courses
maxAuthors: 1
name: Courses
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: true
    template: courses/_entry.twig
    uriFormat: 'courses/{slug}'
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: true
    template: courses/_entry.twig
    uriFormat: 'courses/{slug}'
structure:
  maxLevels: null
  uid: 3e2e4bc9-aa0a-4ae3-8556-cc033b40b085
type: structure
