defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 143b8c67-d15e-44bc-95eb-a1b596d08034 # Dictionary
handle: dictionary
maxAuthors: 1
name: Dictionary
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: true
    template: dictionary/_entry.twig
    uriFormat: 'dictionary/{slug}'
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: true
    template: dictionary/_entry.twig
    uriFormat: 'dictionary/{slug}'
type: channel
