defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6b3fc265-7f98-4050-ac51-be0f944824c3 # HeroUnderSpecialists
handle: herounderspecialists
maxAuthors: 1
name: 'Hero under specialists'
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: true
    template: herounderspecialists/_entry.twig
    uriFormat: 'herounderspecialists/{slug}'
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: true
    template: herounderspecialists/_entry.twig
    uriFormat: 'herounderspecialists/{slug}'
structure:
  maxLevels: null
  uid: f2f2472f-a9a7-4616-a479-0b353efb3062
type: structure
