defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0eeaedd5-ee74-466f-bfe0-63ef3461c81b # HeroData
handle: herodata
maxAuthors: 1
name: 'Hero Data'
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
