defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3318888e-64d2-4901-980c-34079239ba67 # Languages
handle: languages
maxAuthors: 1
name: Languages
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: true
    template: languages/_entry.twig
    uriFormat: 'languages/{slug}'
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: true
    template: languages/_entry.twig
    uriFormat: 'languages/{slug}'
structure:
  maxLevels: null
  uid: b4c95cbc-22f3-4aff-9528-d4277afa6cd1
type: structure
