defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2cd39f42-6d95-4e0f-90bd-11a495e77e2a # Phones
handle: phones
maxAuthors: 1
name: Phones
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: true
    template: phones/_entry.twig
    uriFormat: 'phones/{slug}'
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: true
    template: phones/_entry.twig
    uriFormat: 'phones/{slug}'
structure:
  maxLevels: null
  uid: 5b384046-6a91-45a1-a809-8fa6356860ea
type: structure
