defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: cb6f3a9f-7107-48cd-a1ac-67132be782d7 # Seo data
handle: seoData
maxAuthors: 1
name: 'Seo data'
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: true
    template: seo-data/_entry.twig
    uriFormat: seo-data
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: true
    template: seo-data/_entry.twig
    uriFormat: seo-data
type: single
