defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fd3bd333-8648-4c71-929b-63af660fc5c3 # Services
handle: services
maxAuthors: 1
name: Services
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: true
    template: services/_entry.twig
    uriFormat: 'services/{slug}'
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: true
    template: services/_entry.twig
    uriFormat: 'services/{slug}'
structure:
  maxLevels: null
  uid: ec8e1781-bc11-4978-a79c-adc89abaccd9
type: structure
