defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 92b09090-e729-4e57-b642-992b0133dfa8 # Site information
handle: siteInformation
maxAuthors: 1
name: 'Site information'
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: true
    template: site-information/_entry.twig
    uriFormat: site-information
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: true
    template: site-information/_entry.twig
    uriFormat: site-information
type: single
