defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d986f5c4-b04a-4e2f-bb73-58d68c9a0d9c # University
handle: university
maxAuthors: 1
name: University
previewTargets:
  -
    label: 'Основная запись страница'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a53f373b-5ae8-45fb-bc64-bc75d760227e: # Suat Əsədov
    enabledByDefault: true
    hasUrls: true
    template: university/_entry.twig
    uriFormat: 'university/{slug}'
  e705b9db-b8d7-4d03-bead-e87252e55c98: # Suat Asadov
    enabledByDefault: true
    hasUrls: true
    template: university/_entry.twig
    uriFormat: 'university/{slug}'
structure:
  maxLevels: null
  uid: 04203fbc-d548-4cde-ad17-7a2d94debcda
type: structure
